{% set name = "python-arango" %}
{% set version = "7.5.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-arango-{{ version }}.tar.gz
  sha256: aa19510c9f99cc2089f92fe8b87fd510b3de961b1f5bece4fb754e6f1f8f1f66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - urllib3 >=1.26.0
    - requests
    - requests-toolbelt
    - pyjwt
    - setuptools >=42

about:
  home: https://github.com/ArangoDB-Community/python-arango
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python driver for ArangoDB
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/ArangoDB-Community/python-arango

extra:
  recipe-maintainers:
    - xylar
    - carlodri
    - aMahanna
    - xylar
