{% set name = "python-arango" %}
{% set version = "7.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-arango-{{ version }}.tar.gz
  sha256: 7cbdda51e94adab8618f9d1df3dc557b19b8805237ae8521e348ab88a9e2297c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - urllib3 >=1.26.0
    - requests
    - requests-toolbelt
    - pyjwt
    - setuptools >=42

about:
  home: https://github.com/ArangoDB-Community/python-arango
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python driver for ArangoDB
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/ArangoDB-Community/python-arango

extra:
  recipe-maintainers:
    - xylar
    - carlodri
    - aMahanna
    - xylar
