{% set name = "python-arango" %}
{% set version = "8.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 99a8966c01994e48747bf9c7be96457fe717dd2a1c2b319895d02899fb7344a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - urllib3 >=1.26.0
    - requests
    - requests-toolbelt
    - pyjwt
    - setuptools >=42
    - importlib-metadata >=4.7.1
    - packaging >=23.1

test:
  imports:
    - arango
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ArangoDB-Community/python-arango
  summary: Python Driver for ArangoDB
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/ArangoDB-Community/python-arango

extra:
  recipe-maintainers:
    - xylar
    - carlodri
    - aMahanna
    - xylar
