{% set name = "python-arango" %}
{% set version = "7.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-arango-{{ version }}.tar.gz
  sha256: 8ae893d32220bbf7d0158fd8675a011219076189c82371543df75d650f9d0707

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - urllib3 >=1.26.0
    - requests
    - requests-toolbelt
    - pyjwt
    - setuptools >=42
    - importlib-metadata >=4.7.1
    - packaging >=23.1

about:
  home: https://github.com/ArangoDB-Community/python-arango
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The official Python driver for ArangoDB
  doc_url: https://python-driver-for-arangodb.readthedocs.io/
  dev_url: https://github.com/ArangoDB-Community/python-arango

extra:
  recipe-maintainers:
    - xylar
    - carlodri
    - aMahanna
    - xylar
