schema_version: 1

context:
  name: python-arango
  version: 8.2.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 7f1957c9913133d719063d06e7d6d41650604358d167aae5bcd83ad6f847509d

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=42
    - setuptools-scm
    - pip
  run:
    - python >=${{ python_min }}
    - urllib3 >=1.26.0
    - requests
    - requests-toolbelt
    - pyjwt
    - setuptools >=42
    - importlib-metadata >=4.7.1
    - packaging >=23.1

tests:
  - python:
      imports:
        - arango
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: Python Driver for ArangoDB
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ArangoDB-Community/python-arango
  repository: https://github.com/ArangoDB-Community/python-arango
  documentation: https://python-driver-for-arangodb.readthedocs.io/

extra:
  recipe-maintainers:
    - xylar
    - carlodri
    - aMahanna
    - xylar
